site_name: My Math Notes
theme:
  name: material
  palette: 
    primary: indigo
    accent: indigo

markdown_extensions:
  - pymdownx.arithmatex:
      generic: true

extra_javascript:
  - javascripts/mathjax.js
  - https://polyfill.io/v3/polyfill.min.js?features=es6
  - https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-mml-chtml.js

nav:
  - Home: index.md
  - Algebra:
      - '1.1 Algebra: Fundamentals of Matrices': Algebra/1_1_Algebra.md
      - '1.2 Algebra: Determinants': Algebra/1_2_Algebra.md
      - '1.3 Algebra: The Inverse Matrix': Algebra/1_3_Algebra.md
      - '1.4 Algebra: Systems of Linear Equations': Algebra/1_4_Algebra.md
  - Geometry:
      - '2.1 Geometry: Cartesian Space & Vectors': Geometry/2_1_Geometry.md
      - '2.2 Geometry: Vector Products': Geometry/2_2_Geometry.md
      - '2.3 Geometry: Lines & Planes in Space': Geometry/2_3_Geometry.md
  - Calculus:
      - '3.1 Calculus: Functions & Relations': Calculus/3_1_Calculus.md
      - '3.2 Calculus: Limits': Calculus/3_2_Calculus.md
      - '3.3 Calculus: Derivatives': Calculus/3_3_Calculus.md
      - '3.4 Calculus: Integrals': Calculus/3_4_Calculus.md
      - '3.5 Calculus: Differential Equations': Calculus/3_5_Calculus.md
  - ðŸ§® Interactive Calculator: https://daniel-derivative-calculator.streamlit.app/