site_name: My Math Notes
theme:
  name: material
  palette: 
    primary: indigo
    accent: indigo

markdown_extensions:
  - pymdownx.arithmatex:
      generic: true

extra_javascript:
  - javascripts/mathjax.js
  - https://polyfill.io/v3/polyfill.min.js?features=es6
  - https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-mml-chtml.js

# Añade esto para tener el menú ordenado
nav:
  - Home: index.md
  - Algebra: algebra.md
  - Calculus: calculus.md
  - Geometry: geometry.md
  - Interactive Calculator: https://daniel-derivative-calculator.streamlit.app/