site_name: My Math Notes
theme:
  name: material
  palette: 
    primary: indigo
    accent: indigo

markdown_extensions:
  - pymdownx.arithmatex:
      generic: true

extra_javascript:
  - javascripts/mathjax.js
  - https://polyfill.io/v3/polyfill.min.js?features=es6
  - https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-mml-chtml.js

nav:
  - Home: index.md
  - Algebra:
      - '1_1_Algebra': Algebra/1_1_Algebra.md
      - '1_2_Algebra': Algebra/1_2_Algebra.md
      - '1_3_Algebra': Algebra/1_3_Algebra.md
      - '1_4_Algebra': Algebra/1_4_Algebra.md
  - Geometry:
      - '2_1_Geometry': Geometry/2_1_Geometry.md
      - '2_2_Geometry': Geometry/2_2_Geometry.md
      - '2_3_Geometry': Geometry/2_3_Geometry.md
  - Calculus:
      - '3_1_Calculus': Calculus/3_1_Calculus.md
      - '3_2_Calculus': Calculus/3_2_Calculus.md
      - '3_3_Calculus': Calculus/3_3_Calculus.md
      - '3_4_Calculus': Calculus/3_4_Calculus.md
      - '3_5_Calculus': Calculus/3_5_Calculus.md
  - ðŸ§® Interactive Calculator: https://daniel-derivative-calculator.streamlit.app/